import type { Game } from "./types";

const GAMES: Game[] = [
    // --- 2025 & 2026 BLOCKBUSTER HITS (RPG/ACTION) ---
    {
        id: 1,
        title: "Grand Theft Auto VI",
        category: "Action",
        rating: 5.0,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/271590/library_hero.jpg",
        releaseDate: "2026-10-15",
        price: 79.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/QdBZY2fkU-0"
    },
    {
        id: 2,
        title: "The Elder Scrolls VI",
        category: "RPG",
        rating: 4.9,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/489830/library_hero.jpg",
        releaseDate: "2026-11-11",
        price: 79.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/OkFdqqyI8y4"
    },
    {
        id: 3,
        title: "Monster Hunter Wilds",
        category: "RPG",
        rating: 4.8,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2246340/library_hero.jpg",
        releaseDate: "2025-02-28",
        price: 69.99,
    },
    {
        id: 4,
        title: "Death Stranding 2: On The Beach",
        category: "Action",
        rating: 4.7,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1850570/library_hero.jpg",
        releaseDate: "2025-06-15",
        price: 69.99,
    },
    {
        id: 5,
        title: "Ghost of Yōtei",
        category: "Action",
        rating: 4.9,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2215430/library_hero.jpg",
        releaseDate: "2026-09-20",
        price: 69.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/CbOfmMWmjcA"
    },
    {
        id: 6,
        title: "Assassin's Creed Shadows",
        category: "RPG",
        rating: 4.5,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/3159330/library_hero.jpg",
        releaseDate: "2025-02-14",
        price: 69.99,
    },
    {
        id: 7,
        title: "Kingdom Come: Deliverance II",
        category: "RPG",
        rating: 4.6,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1771300/library_hero.jpg",
        releaseDate: "2025-02-11",
        price: 59.99,
    },
    {
        id: 8,
        title: "Fable",
        category: "RPG",
        rating: 4.6,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/252950/library_hero.jpg",
        releaseDate: "2026-11-20",
        price: 69.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/W3QkOuanGKE"
    },
    {
        id: 9,
        title: "Mass Effect 5 (Epsilon)",
        category: "RPG",
        rating: 4.8,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1328670/library_hero.jpg",
        releaseDate: "2026-12-01",
        price: 79.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/Lg-Ctg6k_Ao"
    },
    {
        id: 10,
        title: "The Witcher 4: Polaris",
        category: "RPG",
        rating: 5.0,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/292030/library_hero.jpg",
        releaseDate: "2026-05-19",
        price: 79.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/54dabgZJ5YA"
    },

    // --- SPORTS & RACING (LATEST VERSIONS) ---
    {
        id: 11,
        title: "EA SPORTS FC™ 26",
        category: "Sports",
        rating: 4.3,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2195250/library_hero.jpg",
        releaseDate: "2025-09-27",
        price: 79.99,
    },
    {
        id: 12,
        title: "NBA 2K26",
        category: "Sports",
        rating: 4.0,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2878980/library_hero.jpg",
        releaseDate: "2025-09-06",
        price: 79.99,
    },
    {
        id: 13,
        title: "F1® 25",
        category: "Racing",
        rating: 4.4,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2488620/library_hero.jpg",
        releaseDate: "2025-05-31",
        price: 69.99,
    },
    {
        id: 14,
        title: "Forza Horizon 6",
        category: "Racing",
        rating: 4.8,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1551360/library_hero.jpg",
        releaseDate: "2025-11-09",
        price: 69.99,
    },
    {
        id: 15,
        title: "eFootball™ 2026",
        category: "Sports",
        rating: 3.5,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1665460/library_hero.jpg",
        releaseDate: "2025-08-25",
        price: 0.00,
    },
    {
        id: 16,
        title: "TopSpin 2K26",
        category: "Sports",
        rating: 4.1,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1785650/library_hero.jpg",
        releaseDate: "2026-04-20",
        price: 69.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 17,
        title: "Assetto Corsa Evo",
        category: "Racing",
        rating: 4.7,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/3025800/library_hero.jpg",
        releaseDate: "2025-01-15",
        price: 49.99,
    },
    {
        id: 18,
        title: "Skate. (4)",
        category: "Sports",
        rating: 4.5,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1785650/library_hero.jpg",
        releaseDate: "2025-07-10",
        price: 0.00,
    },
    {
        id: 19,
        title: "Gran Turismo 8",
        category: "Racing",
        rating: 4.7,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1551360/library_hero.jpg",
        releaseDate: "2026-03-04",
        price: 79.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 20,
        title: "WWE 2K26",
        category: "Sports",
        rating: 4.3,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2315690/library_hero.jpg",
        releaseDate: "2026-03-10",
        price: 69.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },

    // --- FPS & SHOOTER (2025/26) ---
    {
        id: 21,
        title: "DOOM: The Dark Ages",
        category: "FPS",
        rating: 4.9,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/3017860/library_hero.jpg",
        releaseDate: "2025-05-15",
        price: 69.99,
    },
    {
        id: 22,
        title: "Borderlands 4",
        category: "FPS",
        rating: 4.6,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1286680/library_hero.jpg",
        releaseDate: "2025-09-13",
        price: 69.99,
    },
    {
        id: 23,
        title: "Call of Duty: Black Ops 7",
        category: "FPS",
        rating: 4.5,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1938090/library_hero.jpg",
        releaseDate: "2025-10-25",
        price: 79.99,
    },
    {
        id: 24,
        title: "Battlefield 7",
        category: "FPS",
        rating: 4.4,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1517290/library_hero.jpg",
        releaseDate: "2025-11-15",
        price: 69.99,
    },
    {
        id: 25,
        title: "Metroid Prime 4: Beyond",
        category: "FPS",
        rating: 4.8,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1085660/library_hero.jpg",
        releaseDate: "2025-06-20",
        price: 59.99,
    },
    {
        id: 26,
        title: "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
        category: "FPS",
        rating: 4.6,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1643320/library_hero.jpg",
        releaseDate: "2024-11-20",
        price: 59.99,
    },
    {
        id: 27,
        title: "Mafia: The Old Country",
        category: "Action",
        rating: 4.5,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1030830/library_hero.jpg",
        releaseDate: "2025-08-10",
        price: 69.99,
    },
    {
        id: 28,
        title: "Gears of War: E-Day",
        category: "Shooter",
        rating: 4.7,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1097840/library_hero.jpg",
        releaseDate: "2026-06-01",
        price: 69.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/H9Ue7RPOudU"
    },
    {
        id: 29,
        title: "Judas",
        category: "FPS",
        rating: 4.6,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2440650/library_hero.jpg",
        releaseDate: "2025-03-25",
        price: 69.99,
    },
    {
        id: 30,
        title: "Killing Floor 3",
        category: "FPS",
        rating: 4.4,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1430190/library_hero.jpg",
        releaseDate: "2025-04-10",
        price: 49.99,
    },

    // --- STRATEGY & SIMULATION (2025/26) ---
    {
        id: 31,
        title: "Sid Meier's Civilization VII",
        category: "Strategy",
        rating: 4.8,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/289070/library_hero.jpg",
        releaseDate: "2025-02-11",
        price: 69.99,
    },
    {
        id: 32,
        title: "The Sims 5 (Project Rene)",
        category: "Simulation",
        rating: 4.3,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1222670/library_hero.jpg",
        releaseDate: "2026-09-01",
        price: 0.00,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 33,
        title: "Anno 117: Pax Romana",
        category: "Strategy",
        rating: 4.6,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/916440/library_hero.jpg",
        releaseDate: "2025-05-20",
        price: 59.99,
    },
    {
        id: 34,
        title: "Microsoft Flight Simulator 2024",
        category: "Simulation",
        rating: 4.8,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1250410/library_hero.jpg",
        releaseDate: "2024-11-19",
        price: 69.99,
    },
    {
        id: 35,
        title: "Frostpunk 2",
        category: "Strategy",
        rating: 4.5,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1601580/library_hero.jpg",
        releaseDate: "2024-09-20",
        price: 44.99,
    },
    {
        id: 36,
        title: "InZOI",
        category: "Simulation",
        rating: 4.4,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2456740/library_hero.jpg",
        releaseDate: "2025-03-15",
        price: 49.99,
    },
    {
        id: 37,
        title: "Football Manager 2026",
        category: "Simulation",
        rating: 4.6,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2252570/library_hero.jpg",
        releaseDate: "2025-11-06",
        price: 59.99,
    },

    // --- INDIE, ADVENTURE & OTHERS (2025/26) ---
    {
        id: 38,
        title: "Hades II",
        category: "Indie",
        rating: 5.0,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1145360/library_hero.jpg",
        releaseDate: "2025-04-01",
        price: 29.99,
    },
    {
        id: 39,
        title: "Hollow Knight: Silksong",
        category: "Indie",
        rating: 5.0,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1030300/library_hero.jpg",
        releaseDate: "2025-06-01",
        price: 29.99,
    },
    {
        id: 40,
        title: "Little Nightmares III",
        category: "Horror",
        rating: 4.6,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1392860/library_hero.jpg",
        releaseDate: "2025-08-25",
        price: 39.99,
    },
    {
        id: 41,
        title: "Avowed",
        category: "RPG",
        rating: 4.5,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2457220/library_hero.jpg",
        releaseDate: "2025-02-18",
        price: 69.99,
    },
    {
        id: 42,
        title: "Indiana Jones and the Great Circle",
        category: "Action",
        rating: 4.5,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2677660/library_hero.jpg",
        releaseDate: "2024-12-09",
        price: 69.99,
    },
    {
        id: 43,
        title: "Marvel's Wolverine",
        category: "Action",
        rating: 4.8,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1817070/library_hero.jpg",
        releaseDate: "2026-09-10",
        price: 69.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/qnyKrEeHYuE"
    },
    {
        id: 44,
        title: "Wonder Woman",
        category: "Action",
        rating: 4.6,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1085660/library_hero.jpg",
        releaseDate: "2026-07-15",
        price: 69.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 45,
        title: "State of Decay 3",
        category: "Horror",
        rating: 4.4,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/3017860/library_hero.jpg",
        releaseDate: "2025-10-31",
        price: 59.99,
    },
    {
        id: 46,
        title: "BioShock 4 (Isolation)",
        category: "FPS",
        rating: 4.7,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/409710/library_hero.jpg",
        releaseDate: "2026-08-20",
        price: 69.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 47,
        title: "Metal Gear Solid Delta: Snake Eater",
        category: "Action",
        rating: 4.9,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2417610/library_hero.jpg",
        releaseDate: "2025-05-05",
        price: 69.99,
    },
    {
        id: 48,
        title: "Star Wars: Eclipse",
        category: "Action",
        rating: 4.5,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1174180/library_hero.jpg",
        releaseDate: "2026-12-15",
        price: 69.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/4cJpiOPKH14"
    },
    {
        id: 49,
        title: "Vampire: The Masquerade - Bloodlines 2",
        category: "RPG",
        rating: 4.4,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/532790/library_hero.jpg",
        releaseDate: "2025-06-30",
        price: 59.99,
    },
    {
        id: 50,
        title: "Ark 2",
        category: "Survival",
        rating: 4.3,
        coverImage: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/346110/library_hero.jpg",
        releaseDate: "2025-11-15",
        price: 59.99,
        isUpcoming: true,
        trailerUrl: "https://www.youtube.com/embed/QUjtXjFRcAQ"
    },
];

export const fetchGames = async (): Promise<Game[]> => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(GAMES);
        }, 500);
    });
};